// Text for the sample PDF: abridged selections from Book I of Adam Smith's
// "The Wealth of Nations" (1776, public domain). Each string is one paragraph.

export const pdfTitle = 'The Wealth of Nations'
export const pdfSubtitle = 'Selections from Book I, abridged for the ReadHub demo'
export const pdfAuthor = 'Adam Smith (1776)'

export const pdfChapters: { title: string; paragraphs: string[] }[] = [
  {
    title: 'Chapter I. Of the Division of Labour',
    paragraphs: [
      'The greatest improvement in the productive powers of labour, and the greater part of the skill, dexterity, and judgment with which it is anywhere directed, or applied, seem to have been the effects of the division of labour.',
      'The effects of the division of labour, in the general business of society, will be more easily understood by considering in what manner it operates in some particular manufactures. It is commonly supposed to be carried furthest in some very trifling ones; not perhaps that it really is carried further in them than in others of more importance, but because in those trifling manufactures the workmen employed in every different branch of the work can often be collected into the same workhouse, and placed at once under the view of the spectator.',
      'To take an example, therefore, from a very trifling manufacture, but one in which the division of labour has been very often taken notice of, the trade of the pin-maker: a workman not educated to this business, nor acquainted with the use of the machinery employed in it, could scarce, perhaps, with his utmost industry, make one pin in a day, and certainly could not make twenty.',
      'But in the way in which this business is now carried on, not only the whole work is a peculiar trade, but it is divided into a number of branches, of which the greater part are likewise peculiar trades. One man draws out the wire, another straights it, a third cuts it, a fourth points it, a fifth grinds it at the top for receiving the head; to make the head requires two or three distinct operations; to put it on is a peculiar business, to whiten the pins is another; it is even a trade by itself to put them into the paper.',
      'I have seen a small manufactory of this kind where ten men only were employed. Those ten persons could make among them upwards of forty-eight thousand pins in a day. Each person, therefore, making a tenth part of forty-eight thousand pins, might be considered as making four thousand eight hundred pins in a day. But if they had all wrought separately and independently, they certainly could not each of them have made twenty, perhaps not one pin in a day.',
      'This great increase of the quantity of work which, in consequence of the division of labour, the same number of people are capable of performing, is owing to three different circumstances: first, to the increase of dexterity in every particular workman; secondly, to the saving of the time which is commonly lost in passing from one species of work to another; and lastly, to the invention of a great number of machines which facilitate and abridge labour, and enable one man to do the work of many.',
      'First, the improvement of the dexterity of the workman necessarily increases the quantity of the work he can perform; and the division of labour, by reducing every man\'s business to some one simple operation, and by making this operation the sole employment of his life, necessarily increases very much the dexterity of the workman.',
      'Secondly, the advantage which is gained by saving the time commonly lost in passing from one sort of work to another is much greater than we should at first view be apt to imagine. A man commonly saunters a little in turning his hand from one sort of employment to a quite different one. When he first begins the new work he is seldom very keen and hearty; his mind, as they say, does not go to it, and for some time he rather trifles than applies to good purpose.',
      'Thirdly, and lastly, everybody must be sensible how much labour is facilitated and abridged by the application of proper machinery. A great part of the machines made use of in those manufactures in which labour is most subdivided were originally the inventions of common workmen, who, being each of them employed in some very simple operation, naturally turned their thoughts towards finding out easier and readier methods of performing it.',
      'It is the great multiplication of the productions of all the different arts, in consequence of the division of labour, which occasions, in a well-governed society, that universal opulence which extends itself to the lowest ranks of the people.',
    ],
  },
  {
    title: 'Chapter II. Of the Principle which gives occasion to the Division of Labour',
    paragraphs: [
      'This division of labour, from which so many advantages are derived, is not originally the effect of any human wisdom, which foresees and intends that general opulence to which it gives occasion. It is the necessary, though very slow and gradual, consequence of a certain propensity in human nature which has in view no such extensive utility: the propensity to truck, barter, and exchange one thing for another.',
      'Whether this propensity be one of those original principles in human nature of which no further account can be given; or whether, as seems more probable, it be the necessary consequence of the faculties of reason and speech, it belongs not to our present subject to inquire. It is common to all men, and to be found in no other race of animals. Nobody ever saw a dog make a fair and deliberate exchange of one bone for another with another dog.',
      'In civilized society man stands at all times in need of the co-operation and assistance of great multitudes, while his whole life is scarce sufficient to gain the friendship of a few persons. Man has almost constant occasion for the help of his brethren, and it is in vain for him to expect it from their benevolence only. He will be more likely to prevail if he can interest their self-love in his favour, and show them that it is for their own advantage to do for him what he requires of them.',
      'Give me that which I want, and you shall have this which you want, is the meaning of every such offer; and it is in this manner that we obtain from one another the far greater part of those good offices which we stand in need of. It is not from the benevolence of the butcher, the brewer, or the baker that we expect our dinner, but from their regard to their own interest. We address ourselves, not to their humanity but to their self-love, and never talk to them of our own necessities but of their advantages.',
      'As it is by treaty, by barter, and by purchase that we obtain from one another the greater part of those mutual good offices which we stand in need of, so it is this same trucking disposition which originally gives occasion to the division of labour. In a tribe of hunters or shepherds a particular person makes bows and arrows with more readiness and dexterity than any other. He frequently exchanges them for cattle or for venison with his companions; and he finds at last that he can in this manner get more cattle and venison than if he himself went to the field to catch them.',
      'The difference of natural talents in different men is, in reality, much less than we are aware of; and the very different genius which appears to distinguish men of different professions, when grown up to maturity, is not upon many occasions so much the cause as the effect of the division of labour. The difference between the most dissimilar characters, between a philosopher and a common street porter, for example, seems to arise not so much from nature as from habit, custom, and education.',
    ],
  },
  {
    title: 'Chapter III. That the Division of Labour is limited by the Extent of the Market',
    paragraphs: [
      'As it is the power of exchanging that gives occasion to the division of labour, so the extent of this division must always be limited by the extent of that power, or, in other words, by the extent of the market. When the market is very small, no person can have any encouragement to dedicate himself entirely to one employment, for want of the power to exchange all that surplus part of the produce of his own labour, which is over and above his own consumption, for such parts of the produce of other men\'s labour as he has occasion for.',
      'There are some sorts of industry, even of the lowest kind, which can be carried on nowhere but in a great town. A porter, for example, can find employment and subsistence in no other place. A village is by much too narrow a sphere for him; even an ordinary market town is scarce large enough to afford him constant occupation.',
      'In the lone houses and very small villages which are scattered about in so desert a country as the Highlands of Scotland, every farmer must be butcher, baker, and brewer for his own family. A country carpenter deals in every sort of work that is made of wood: he is not only a carpenter, but a joiner, a cabinet-maker, and even a carver in wood, as well as a wheelwright, a ploughwright, a cart and waggon maker.',
      'As by means of water-carriage a more extensive market is opened to every sort of industry than what land-carriage alone can afford it, so it is upon the sea-coast, and along the banks of navigable rivers, that industry of every kind naturally begins to subdivide and improve itself, and it is frequently not till a long time after that those improvements extend themselves to the inland parts of the country.',
      'A broad-wheeled waggon, attended by two men and drawn by eight horses, in about six weeks\' time carries and brings back between London and Edinburgh near four ton weight of goods. In about the same time a ship navigated by six or eight men, and sailing between the ports of London and Leith, frequently carries and brings back two hundred ton weight of goods.',
      'Since such, therefore, are the advantages of water-carriage, it is natural that the first improvements of art and industry should be made where this conveniency opens the whole world for a market to the produce of every sort of labour.',
    ],
  },
  {
    title: 'Chapter IV. Of the Origin and Use of Money',
    paragraphs: [
      'When the division of labour has been once thoroughly established, it is but a very small part of a man\'s wants which the produce of his own labour can supply. He supplies the far greater part of them by exchanging that surplus part of the produce of his own labour for such parts of the produce of other men\'s labour as he has occasion for. Every man thus lives by exchanging, or becomes in some measure a merchant, and the society itself grows to be what is properly a commercial society.',
      'But when the division of labour first began to take place, this power of exchanging must frequently have been very much clogged and embarrassed in its operations. The butcher has more meat in his shop than he himself can consume, and the brewer and the baker would each of them be willing to purchase a part of it. But they have nothing to offer in exchange, except the different productions of their respective trades, and the butcher is already provided with all the bread and beer which he has immediate occasion for.',
      'In order to avoid the inconveniency of such situations, every prudent man in every period of society, after the first establishment of the division of labour, must naturally have endeavoured to manage his affairs in such a manner as to have at all times by him, besides the peculiar produce of his own industry, a certain quantity of some one commodity or other, such as he imagined few people would be likely to refuse in exchange for the produce of their industry.',
      'Many different commodities, it is probable, were successively both thought of and employed for this purpose. In the rude ages of society, cattle are said to have been the common instrument of commerce. Salt is said to be the common instrument of commerce and exchanges in Abyssinia; a species of shells in some parts of the coast of India; dried cod at Newfoundland; tobacco in Virginia; sugar in some of our West India colonies.',
      'In all countries, however, men seem at last to have been determined by irresistible reasons to give the preference, for this employment, to metals above every other commodity. Metals can not only be kept with as little loss as any other commodity, scarce anything being less perishable than they are, but they can likewise, without any loss, be divided into any number of parts, as by fusion those parts can easily be reunited again.',
      'The use of metals in this rude state was attended with two very considerable inconveniencies: first, with the trouble of weighing; and secondly, with that of assaying them. To prevent such abuses, to facilitate exchanges, and thereby to encourage all sorts of industry and commerce, it has been found necessary, in all countries that have made any considerable advances towards improvement, to affix a public stamp upon certain quantities of such particular metals. Hence the origin of coined money.',
      'It is to be observed that the word value has two different meanings, and sometimes expresses the utility of some particular object, and sometimes the power of purchasing other goods which the possession of that object conveys. The one may be called value in use; the other, value in exchange.',
      'The things which have the greatest value in use have frequently little or no value in exchange; and, on the contrary, those which have the greatest value in exchange have frequently little or no value in use. Nothing is more useful than water: but it will purchase scarce anything; scarce anything can be had in exchange for it. A diamond, on the contrary, has scarce any value in use; but a very great quantity of other goods may frequently be had in exchange for it.',
    ],
  },
]
